name: Merge upstream branches
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'SmartIotMaker'
          git config --global user.email 'john.zhouhua@gmail.com'
          
          git pull
          git remote add upstream https://github.com/openwrt/openwrt.git
          git fetch upstream
          
          git branch -r | grep -v '\->' | grep -v 'upstream' | while read remote; \
              do \
                  git checkout -b ${remote#origin/} origin/${remote#origin/}; \
                  git merge --no-edit upstream/${remote#origin/} \
                  echo ${remote#origin/}
              done
              
