name: Merge upstream branches
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/openwrt/openwrt.git
          
          git branch -r | grep -v '\->' | grep -v 'upstream' | while read remote; \
              do \
                  git checkout ${remote#origin/}; \
                  git merge --ff-only upstream/${remote#origin/}; \
                  git push origin ${remote#origin/};
              done
        shell: bash
