name: Merge upstream branches
on:
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git pull --unshallow
          git remote add upstream https://github.com/openwrt/openwrt.git
          
          git checkout origin/openwrt-18.06
          git merge --ff-only  upstream/openwrt-18.06
          git push origin openwrt-18.06
        shell: bash
