#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: openwrt-19.07

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:
          cat >> .config <<EOF
          CONFIG_TARGET_ar71xx=y
          CONFIG_TARGET_ar71xx_generic=y
          CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr703n-v1=y
          CONFIG_ALL_KMODS=y
          CONFIG_ALL_NONSHARED=y
          CONFIG_DEVEL=y
          CONFIG_AUTOREMOVE=y
          CONFIG_BUILDBOT=y
          CONFIG_IB=y
          CONFIG_IMAGEOPT=y
          CONFIG_JSON_OVERVIEW_IMAGE_INFO=y
          CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
          CONFIG_KERNEL_BUILD_USER="builder"
          # CONFIG_KERNEL_KALLSYMS is not set
          CONFIG_OPENSSL_ENGINE=y
          CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y
          CONFIG_OPENSSL_WITH_ASM=y
          CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
          CONFIG_OPENSSL_WITH_CMS=y
          CONFIG_OPENSSL_WITH_DEPRECATED=y
          CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
          CONFIG_OPENSSL_WITH_PSK=y
          CONFIG_OPENSSL_WITH_SRP=y
          CONFIG_OPENSSL_WITH_TLS13=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_6rd=y
          CONFIG_PACKAGE_6to4=y
          CONFIG_PACKAGE_adb=m
          CONFIG_PACKAGE_adb-enablemodem=m
          CONFIG_PACKAGE_ath10k-firmware-qca9887-ct=m
          CONFIG_PACKAGE_ath10k-firmware-qca9888-ct=m
          CONFIG_PACKAGE_ath10k-firmware-qca988x-ct=m
          CONFIG_PACKAGE_ath10k-firmware-qca9984-ct=m
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_cgi-io=y
          CONFIG_PACKAGE_dnsmasq-dhcpv6=y
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_dnsmasq_full_auth=y
          CONFIG_PACKAGE_dnsmasq_full_conntrack=y
          CONFIG_PACKAGE_dnsmasq_full_dhcp=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_dnsmasq_full_dnssec=y
          CONFIG_PACKAGE_dnsmasq_full_ipset=y
          CONFIG_PACKAGE_dnsmasq_full_noid=y
          CONFIG_PACKAGE_dnsmasq_full_tftp=y
          CONFIG_PACKAGE_e2fsprogs=m
          CONFIG_PACKAGE_fconfig=m
          CONFIG_PACKAGE_fritz-tffs=m
          CONFIG_PACKAGE_ip-bridge=y
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_ipip=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_ipset-dns=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_iptraf-ng=y
          CONFIG_PACKAGE_iputils-arping=y
          CONFIG_PACKAGE_iputils-clockdiff=y
          CONFIG_PACKAGE_iputils-ping=y
          CONFIG_PACKAGE_iputils-ping6=y
          CONFIG_PACKAGE_iputils-tftpd=y
          CONFIG_PACKAGE_iputils-tracepath=y
          CONFIG_PACKAGE_iputils-tracepath6=y
          CONFIG_PACKAGE_iputils-traceroute6=y
          CONFIG_PACKAGE_ipvsadm=y
          CONFIG_PACKAGE_kmod-arptables=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-crypto-acompress=y
          CONFIG_PACKAGE_kmod-crypto-aead=y
          CONFIG_PACKAGE_kmod-crypto-authenc=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-iv=y
          CONFIG_PACKAGE_kmod-crypto-manager=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-null=y
          CONFIG_PACKAGE_kmod-crypto-pcompress=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-sha1=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-crypto-wq=y
          CONFIG_PACKAGE_kmod-ebtables=y
          CONFIG_PACKAGE_kmod-ebtables-ipv4=y
          CONFIG_PACKAGE_kmod-ebtables-ipv6=y
          CONFIG_PACKAGE_kmod-ebtables-watchers=y
          CONFIG_PACKAGE_kmod-ip6-tunnel=y
          CONFIG_PACKAGE_kmod-ip6tables-extra=y
          CONFIG_PACKAGE_kmod-ipip=y
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-account=y
          CONFIG_PACKAGE_kmod-ipt-chaos=y
          CONFIG_PACKAGE_kmod-ipt-checksum=y
          CONFIG_PACKAGE_kmod-ipt-cluster=y
          CONFIG_PACKAGE_kmod-ipt-clusterip=y
          CONFIG_PACKAGE_kmod-ipt-compat-xtables=y
          CONFIG_PACKAGE_kmod-ipt-condition=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-label=y
          CONFIG_PACKAGE_kmod-ipt-debug=y
          CONFIG_PACKAGE_kmod-ipt-delude=y
          CONFIG_PACKAGE_kmod-ipt-dhcpmac=y
          CONFIG_PACKAGE_kmod-ipt-dnetmap=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-filter=y
          CONFIG_PACKAGE_kmod-ipt-fuzzy=y
          CONFIG_PACKAGE_kmod-ipt-geoip=y
          CONFIG_PACKAGE_kmod-ipt-hashlimit=y
          CONFIG_PACKAGE_kmod-ipt-iface=y
          CONFIG_PACKAGE_kmod-ipt-ipmark=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-ipp2p=y
          CONFIG_PACKAGE_kmod-ipt-iprange=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-ipt-ipv4options=y
          CONFIG_PACKAGE_kmod-ipt-led=y
          CONFIG_PACKAGE_kmod-ipt-length2=y
          CONFIG_PACKAGE_kmod-ipt-logmark=y
          CONFIG_PACKAGE_kmod-ipt-lscan=y
          CONFIG_PACKAGE_kmod-ipt-lua=y
          CONFIG_PACKAGE_kmod-ipt-nat-extra=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-ipt-nathelper-rtsp=y
          CONFIG_PACKAGE_kmod-ipt-nflog=y
          CONFIG_PACKAGE_kmod-ipt-nfqueue=y
          CONFIG_PACKAGE_kmod-ipt-physdev=y
          CONFIG_PACKAGE_kmod-ipt-psd=y
          CONFIG_PACKAGE_kmod-ipt-quota2=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-ipt-raw6=y
          CONFIG_PACKAGE_kmod-ipt-rpfilter=y
          CONFIG_PACKAGE_kmod-ipt-sysrq=y
          CONFIG_PACKAGE_kmod-ipt-tarpit=y
          CONFIG_PACKAGE_kmod-ipt-tee=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-ipt-u32=y
          CONFIG_PACKAGE_kmod-ipt-ulog=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-textsearch=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-nat46=y
          CONFIG_PACKAGE_kmod-netatop=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_kmod-nf-ipvs=y
          CONFIG_PACKAGE_kmod-nf-ipvs-ftp=y
          CONFIG_PACKAGE_kmod-nf-ipvs-sip=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-nathelper=y
          CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
          CONFIG_PACKAGE_kmod-nfnetlink=y
          CONFIG_PACKAGE_kmod-nfnetlink-log=y
          CONFIG_PACKAGE_kmod-nfnetlink-queue=y
          CONFIG_PACKAGE_kmod-nft-arp=y
          CONFIG_PACKAGE_kmod-nft-bridge=y
          CONFIG_PACKAGE_kmod-nft-core=y
          CONFIG_PACKAGE_kmod-nft-fib=y
          CONFIG_PACKAGE_kmod-nft-nat=y
          CONFIG_PACKAGE_kmod-nft-nat6=y
          CONFIG_PACKAGE_kmod-nft-netdev=y
          CONFIG_PACKAGE_kmod-nft-offload=y
          CONFIG_PACKAGE_kmod-nls-base=m
          CONFIG_PACKAGE_kmod-rtc-pcf2123=m
          CONFIG_PACKAGE_kmod-rtc-pcf8563=m
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sched-ipset=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_kmod-udptunnel4=y
          CONFIG_PACKAGE_kmod-udptunnel6=y
          CONFIG_PACKAGE_kmod-usb-core=m
          CONFIG_PACKAGE_kmod-usb-ehci=m
          CONFIG_PACKAGE_kmod-usb2=m
          CONFIG_PACKAGE_kmod-wireguard=y
          CONFIG_PACKAGE_libblkid=m
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcomerr=m
          CONFIG_PACKAGE_libelf=y
          CONFIG_PACKAGE_libext2fs=m
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_libiwinfo-lua=y
          CONFIG_PACKAGE_liblua=y
          CONFIG_PACKAGE_liblucihttp=y
          CONFIG_PACKAGE_liblucihttp-lua=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libmnl=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libnetfilter-conntrack=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnfnetlink=y
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_libpopt=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libss=m
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libsysfs=y
          CONFIG_PACKAGE_libubus-lua=y
          CONFIG_PACKAGE_libuuid=m
          CONFIG_PACKAGE_lua=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-lib-ip=y
          CONFIG_PACKAGE_luci-lib-jsonc=y
          CONFIG_PACKAGE_luci-lib-nixio=y
          CONFIG_PACKAGE_luci-mod-admin-full=y
          CONFIG_PACKAGE_luci-mod-network=y
          CONFIG_PACKAGE_luci-mod-status=y
          CONFIG_PACKAGE_luci-mod-system=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_om-watchdog=m
          CONFIG_PACKAGE_relayd=y
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_rpcd=y
          CONFIG_PACKAGE_rpcd-mod-file=y
          CONFIG_PACKAGE_rpcd-mod-iwinfo=y
          CONFIG_PACKAGE_rpcd-mod-luci=y
          CONFIG_PACKAGE_rpcd-mod-rrdns=y
          CONFIG_PACKAGE_rssileds=m
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_stunnel=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_uhttpd=y
          CONFIG_PACKAGE_vsc7385-ucode-pb44=m
          CONFIG_PACKAGE_vsc7395-ucode-pb44=m
          CONFIG_PACKAGE_wireguard=y
          CONFIG_PACKAGE_wireguard-tools=y
          CONFIG_PACKAGE_zerotier=y
          CONFIG_PACKAGE_zlib=y
          CONFIG_SDK=y
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          CONFIG_VERSIONOPT=y
          CONFIG_VERSION_BUG_URL=""
          CONFIG_VERSION_CODE=""
          CONFIG_VERSION_CODE_FILENAMES=y
          CONFIG_VERSION_DIST="OpenWrt"
          CONFIG_VERSION_FILENAMES=y
          CONFIG_VERSION_HOME_URL=""
          CONFIG_VERSION_HWREV=""
          CONFIG_VERSION_MANUFACTURER=""
          CONFIG_VERSION_MANUFACTURER_URL=""
          CONFIG_VERSION_NUMBER=""
          CONFIG_VERSION_PRODUCT=""
          CONFIG_VERSION_REPO="http://downloads.openwrt.org/releases/19.07.0"
          CONFIG_VERSION_SUPPORT_URL=""
          # CONFIG_COLLECT_KERNEL_DEBUG is not set

          EOF
          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
